version: "3.8"

services:
  web:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app 
  api:
    build: ./api
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/club-cricket
      PORT: 3001
    volumes:
      - ./api:/app
    command: ./docker-entrypoint.sh
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - club-cricket:/data/db

volumes:
  club-cricket:
